### ISSUE TITLE
Constraint error in CompletionsPadSupplyBalanceRule for strategic model

### ISSUE THREAD

**Issue by nareshsusarla** [project-pareto/project-pareto#147]
The following line in the strategic model should be 
constraint = (

https://github.com/project-pareto/project-pareto/blob/de8d6a077003929e99f598679418fe0257d9b850/pareto/strategic_water_management/strategic_produced_water_optimization.py#L2272

**Comment by ksbeattie** [comment]
Addressed by #151, but test needed as described in #150.
