### ISSUE TITLE
Update KPIs for Treatment

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#154]
With the new streams that the Treatment development has created, there is a need for more KPIs reported in the summary output,

- [x] volume of residual water
- [x] volume of water sent out of system (post desalination)
- [x] volume of water evaporated
- [x] recycled water should be split into recycled in system and recycled out of system
- [x] update recycling rate to be (water sent to completions in system) / (completions demand in system)
- [ ] facility utilization - not clear how this should be calculated. 
- [x] Miguel received feedback during our demo session to add carbon foot print  / carbon credits to the KPI's. We might need to brainstorm the best way to get this, Trucking avoided, injection, pumping, freshwater pumping, etc.

... potentially more

**Comment by lbianchi-lbl** [comment]
This is mostly done in a forthcoming PR that's not planned or required to be in the March release.

**Comment by lbianchi-lbl** [comment]
A PR for this is coming soon and should be part of the July release.
