### ISSUE TITLE
Updates to Case Studies - all case studies should be runnable

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#194]
- [x] remove unused toy case study problems - (save on BOX for future development)
- [x] add Toy Case study for MINLP (#197)
- [x] Add documentation for case studies: overview, figures (network, PP rates, CP demands, CP flowback, Treatment technologies,)

**Comment by tarnold17** [comment]
The strategic model toy case studies (`strategic_water_treatment_toy_case_study_t10.xlsx`, `strategic_water_treatment_toy_case_study_t10.xlsx`, and `strategic_water_treatment_toy_case_study_t10.xlsx`) are very out of date. I have recently been developing a toy case study which will be a replacement. I will post a PR to merge it into main soon.
