### ISSUE TITLE
Report generation runtime differs drastically depending on system

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#196]
Some machines seem to generate report, even for larger case studies, in seconds, Other machines take minutes to generate report. 
What causes these differences? is it versions of libraries? how can we ensure that UI is running as fast as possible.

**Comment by lbianchi-lbl** [comment]
### Profiling Python code

```sh
python -m cProfile -o report.prof python script_to_profile.py
pip install snakeviz
python -m snakeviz report.prof
```

### Possible causes for slowness

**NOTE**: this is just an unsubstantiated guess without profiling first

- Repeatedly appending rows to a `pandas.DataFrame` is very slow
- The recommended alternative is to use a `list` object for the accumulation, and create the DataFrame once at the end

```py
generated = []
for input_obj in long_list_of_report_items:
     dictlike_output = get_report_data(input_obj)
    generated.append(dictlike_output)
report_table = pd.DataFrame(generated)
```

**Comment by tarnold17** [comment]
Is this still a problem or priority for anyone? If not, I'd recommend closing the issue as not planned.

**Comment by ksbeattie** [comment]
Closing this until some steps to reproduce this can be found.
