### ISSUE TITLE
PARETO Infrastructure Buildout Timing Recommendations

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#212]
A couple approaches discussed, but yet to be finalized:

- Add post processing "ready by" dates. These dates can be determined by the utilization. First time a pipeline is used is the ready by date
- First, PARETO solves as is. Next, PARETO introduces timing decisions for infrastructure. The flows and selected CAPEX is fixed, but PARETO then solves for timing of buildout.

**Comment by tarnold17** [comment]
Closed with #272.
