### ISSUE TITLE
Investigate strategic Permian demo returning infeasible for water quality post processing with Gurobi 

### ISSUE THREAD

**Issue by tarnold17** [project-pareto/project-pareto#213]
When solving with Gurobi (with scaling either on or off), and `WaterQuality.post_process` selected for the `water_quality` build option, the strategic Permian demo reports an infeasible model for the post processing calculations.

An interesting note - if one solves this problem instead with CBC with scaling turned on, there are no problems.

**Comment by melody-shellman** [comment]
- only an issue with Gurobi
- infeasible solution returned from Gurobi (not just the feasibility checker)

**Comment by melody-shellman** [comment]
I believe this is an issue with scaling. Here's what supports that:

- The first step of the post_processing of water quality solves the model without quality and fixes the solution.
- While fixing all variables, if a value is < 0.0000001, it is rounded to 0. Gurobi seems to have some interesting behavior in that optimal solutions are sometimes not actually optimal (tolerances being a factor) 
- I tested changing this threshold to 0.00001, and the problem now solves. 

Other notes:
- Running with scaling increases the size of these 'zero' values from (R04 to S04 T37) 10^-5 to 10^-2

**Comment by tarnold17** [comment]
@melody-shellman good to know. Perhaps we should discuss this with the rest of the team at tomorrow afternoon's treatment meeting. It sounds like the solution is some form of "improve scaling", but do you have any ideas more specifically than that how we should proceed?

**Comment by melody-shellman** [comment]
Related to #209, will likely be resolved with the same solution

**Comment by melody-shellman** [comment]
PR #214 resolved this issue with a correction to the post_process water quality treatment center constraints.
