### ISSUE TITLE
Operational model out of memory /inefficiencies

### ISSUE THREAD

**Issue by apd-lyang** [project-pareto/project-pareto#223]
For a case study with ~700 wellpads and 28 time periods, the operational model runs out of memory.  In a run with one time period, 4,588,038 variables are generated but 4,581,688 were removed during preprocessing.  The inefficiencies that need to be addressed are:

- variable creation: a number of variables such as 'v_C_Piped' are indexed over (L,L'), most of the arcs are not needed and shouldn't be generated in the first place 
- (0/1) parameters to indicate existence of an arc: instead of using these parameters, sets should be used to check whether an arc exists when generating variables and constraints for more efficient Python runs

**Comment by melody-shellman** [comment]
Closed by #241
