### ISSUE TITLE
Address CodeCov upload failures

### ISSUE THREAD

**Issue by lbianchi-lbl** [project-pareto/project-pareto#224]
- [x] Short/medium-term solution: move the Codecov upload step to a separate dependent job so when it fails it can be restarted without having to re-run the test suite
- [ ] Long-term solution: move the Codecov upload step to a separate dependent _workflow_ that is able to access repository secrets so that a dedicated Codecov auth token can be used (as opposed to relying on the GHA "no tokens needed" default we have now, which is likely what's being causing the failures)

**Comment by lbianchi-lbl** [comment]
Moving this to normal priority since the short-term solution from #225 seems to be working OK (occasional failures still occur, but not having to wait for the tests make this more bearable).

**Comment by ksbeattie** [comment]
Closing this as the current solution has been good enough.
