### ISSUE TITLE
Unexpected Behavior to Load Strategic Case without Network Nodes

### ISSUE THREAD

**Issue by pulsipher** [project-pareto/project-pareto#235]
I have a case study that doesn't have any network nodes. This causes problems for building the strategic model. Specifically, instead of reading in the arcs to a network set (e.g., `SNA`)  as an empty dictionary in `df_parameters`, it parses the label (e.g., `{'NetworkNodes': {}` for `NNA`) which causes a dimension error for defining `s_LLA`. 
https://github.com/project-pareto/project-pareto/blob/972967ecd1a918bc641b384a20591b195f1dd44d/pareto/strategic_water_management/strategic_produced_water_optimization.py#L365-L383
Moreover, I can not just delete the tabs in the input file since they are hardcoded in the model as shown above. 

If instead, I specify all the nodes of the type there are (e.g., production pads) and leave the column labels empty (there are no network nodes), then it parses a dictionary that doesn't make sense (e.g., `{(0, 'ProductionPads'): 'PP-A01', (1, 'ProductionPads'): 'PP-A02'}` for `PNA`).

Finally, I can resolve the problem if I ensure I have the tab but it is entirely empty. This is what I currently do, but it would be nicer to not have to have these tabs at all if I don't need them. Also, it seems some sanity checks are needed to prevent problems like this that can take hours to diagnose for those that don't know about these implicit assumptions for the Excel format.

**Comment by ksbeattie** [comment]
Should be addressed by #291

**Comment by melody-shellman** [comment]
This is addressed by #291. Network nodes and network arcs (e.g. PNA,NNA, CNA, etc.) can now be removed from an input sheet and PARETO will still run. The configuration option "pipeline_cost", will still minimally require one or more tabs regardless of which option is selected. An example is "PipelineCost.capacity_based" option will require "PipelineCapexCapacityBased". An empty tab for "PipelineCapexCapacityBased" will resolve the issue.
