### ISSUE TITLE
Strategic Model Excludes Many Trucking Arc Sets

### ISSUE THREAD

**Issue by pulsipher** [project-pareto/project-pareto#236]
The `LLT` set only reads in 6 of the possible trucking sets:
https://github.com/project-pareto/project-pareto/blob/972967ecd1a918bc641b384a20591b195f1dd44d/pareto/strategic_water_management/strategic_produced_water_optimization.py#L384-L394
However, the documentation details the use of 13 possible trucking sets and I need these for case studies I am developing.

**Comment by tarnold17** [comment]
I have pushed a change to address this issue in PR #255, although it probably will be a while until that PR merges.
