### ISSUE TITLE
Incorrect units display for Display Operating Capacity input tab

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#287]
![image](https://github.com/project-pareto/project-pareto/assets/91741082/4991f916-f7dd-4833-90c7-08cd3abc6314)

These units should be %. I think this may be an error from one of PARETO repo methods. @MichaelPesce can you confirm if this is an issue from PARETO reop vs PARETO UI repo?

**Comment by MichaelPesce** [comment]
@melody-shellman yeah the UI is getting the units from a function in the PARETO repo, see: 
https://github.com/project-pareto/project-pareto/blob/main/pareto/utilities/get_data.py#L319-L469
