### ISSUE TITLE
Add instructions to documentation FAQ on how to address “No available solver found among choices: ((‘cbc’,),)” error

### ISSUE THREAD

**Issue by tarnold17** [project-pareto/project-pareto#312]
We have had several users report getting an error message “No available solver found among choices: ((‘cbc’,),)” when trying to run the UI. The advice we have given to these users is to download the CBC binary and copy it to the correct location on their machine. We should add these instructions to the "FAQ" section in the documentation.

**Comment by ksbeattie** [comment]
A suggestion to try and reproduce this would be to try this with the network on your machine disabled.  If this reproduces it, then we could catch it and present a clearer error/warning for the user, instructing them on how to proceed.
